### ISSUE TITLE
Update certain objects in the file

### ISSUE THREAD

**Issue by rromic** [genelet/determined#1]
hello,

thanks for creating this interesting project!

I do have a question regarding updating certain values of some objects within hcl file.

How that can be achived by using this lib?
For example if i dont care for all objects and their spec but only for few of them, how can i make it work with using this lib, in the way that I just update values of some attribute and save to the same file?

Is that something that can be done with unmarshaling or we have to read hcl file line by line to find matching atrribute and replace its value?

**Comment by genelet** [comment]
The current version v1.7.1 should have addressed your question. Use package "determined/convert".

**Comment by rromic** [comment]
Thank you very much on your update!
